//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickedOffModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TickedOffEntities : DbContext
    {
        public TickedOffEntities()
            : base("name=TickedOffEntities")
        {
            Bookings = Set<Booking>();
            Customers = Set<Customer>();
            Inventories = Set<Inventory>();
            Pets = Set<Pet>();
            States = Set<State>();
            Stays = Set<Stay>();
            Staffs = Set<Staff>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Booking> Bookings { get; set; }
        internal virtual DbSet<Customer> Customers { get; set; }
        internal virtual DbSet<Inventory> Inventories { get; set; }
        internal virtual DbSet<Pet> Pets { get; set; }
        internal virtual DbSet<State> States { get; set; }
        internal virtual DbSet<Stay> Stays { get; set; }
        internal virtual DbSet<Staff> Staffs { get; set; }
    }
}
