//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickedOffModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Pet
    {
        public Pet()
        {
            this.Bookings = new HashSet<Booking>();
            this.Stays = new HashSet<Stay>();
        }
    
        public int PetID { get; set; }
        public string PetName { get; set; }
        public string Species { get; set; }
        public string Breed { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        internal virtual ICollection<Booking> Bookings { get; set; }
        internal virtual Customer Customer { get; set; }
        internal virtual ICollection<Stay> Stays { get; set; }
    }
}
