//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickedOffModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class State
    {
        public State()
        {
            this.Customers = new HashSet<Customer>();
            this.Staff = new HashSet<Staff>();
        }
    
        public string Name { get; set; }
    
        internal virtual ICollection<Customer> Customers { get; set; }
        internal virtual ICollection<Staff> Staff { get; set; }
    }
}
