//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickedOffModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Stay
    {
        public int StayID { get; set; }
        public Nullable<System.DateTime> StayStartDate { get; set; }
        public Nullable<System.DateTime> StayEndDate { get; set; }
        public Nullable<int> PetID { get; set; }
        public Nullable<decimal> StayCost { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
